//@ sourceMappingURL=client.map
// Generated by CoffeeScript 1.6.1
(function() {

  (function($) {
    return $(document).ready(function() {
      var socket;
      return socket = io.connect(document.URL.match(/^http:\/\/[^/]*/));
    });
  })(jQuery);

}).call(this);
