//@ sourceMappingURL=model.map
// Generated by CoffeeScript 1.6.1
(function() {
  var Achievement, User;

  User = (function() {

    function User(name, group) {
      ({
        this.name: name,
        this.group: group
      });
    }

    return User;

  })();

  (function() {

    function _Class() {}

    return _Class;

  })();

  Achievement = (function() {

    function Achievement(name, time, pries) {
      ({
        this.name: name,
        this.time: time,
        this.pries: pries
      });
    }

    return Achievement;

  })();

}).call(this);
