//@ sourceMappingURL=index.map
// Generated by CoffeeScript 1.6.1
(function() {

  exports.index = function(req, res) {
    return res.render('index', {
      title: 'Рейтинг достижений'
    });
  };

  require('./index2').init(exports);

  exports.index3 = function(req, res) {
    return res.render('index', {
      title: 'This is index 3'
    });
  };

}).call(this);
