//@ sourceMappingURL=index2.map
// Generated by CoffeeScript 1.6.1
(function() {
  var index2;

  index2 = function(req, res) {
    return res.render('layout', {
      title: "bla bla bla"
    });
  };

  exports.init = function(exports) {
    return exports.index2 = index2;
  };

}).call(this);
